### PR TITLE
Fix A Typo in document.js

### PR DESCRIPTION
**Pull request by hanydd**
- [x] I agree to license my contribution under GPL-3.0 and agree to allow distribution on app stores as outlined in [LICENSE-APPSTORE](https://github.com/ajayyy/maze-utils/blob/master/LICENSE-APPSTORE.txt)

Not sure what the alert is for, but I'm fairly confident that "hae" is not a word.

### CODE REVIEW

**Comment by hanydd** [comment]
I just realized that I also removed a bunch of whitespaces in the commit. If it bothers you, I can go back and make the commit only have 1 changed line.

**Comment by ajayyy** [comment]
yea, if you could do that it would be nice

**Comment by hanydd** [comment]
> yea, if you could do that it would be nice

force pushed, it should be fine now.

**Comment by ajayyy** [comment]
Thanks

**Pull request merged**
