### PR TITLE
Improve performance on Invidious

### PR DESCRIPTION
**Pull request by raphj**
This series of commits improves performance on Invidious.

- It improves waitForElement such that when it is called and the dom is not ready, a mutation observer is only set up if the element is not found after DOMContentLoaded. If all elements that we are trying to find are always there on page load, the mutation observer is never set up. Which is the case on Invidious.
- We wait for YouTube-specific elements `.ytp-inline-preview-u` `a.ytp-title-link[data-sessionlink='feature=player-title']` only on YouTube URL. Waiting for them on Invidious trigger the creation of the aforementioned mutation observer.
- adds invidious to the video exception in isVisible 

I believe `waitForElement` could be further improved by disconnecting the mutation observer when there are no elements to wait anymore.

### CODE REVIEW

**Comment by ajayyy** [comment]
> I believe waitForElement could be further improved by disconnecting the mutation observer when there are no elements to wait anymore.

It does do that already

**Comment by raphj** [comment]
> It does do that already

I should have double checked this before writing this. Sorry!

**Comment by ajayyy** [comment]
> adds invidious to the video exception in isVisible

is there a specific reason for doing this?

**Comment by raphj** [comment]
> > adds invidious to the video exception in isVisible
> 
> is there a specific reason for doing this?

Hello,
sorry for the late answer, I've been busy.

I don't remember quite well why I did it this way, and it's probably incorrect. However, I did find that isVisible returns false for the video player on Invidious on page load, while it seems visible (I see it on the screen). I'm not sure why, and how to fix this. Do you also observe this?

**Comment by ajayyy** [comment]
I believe a few of these changes are unnecessary and I have removed them.

> It improves waitForElement such that when it is called and the dom is not ready, a mutation observer is only set up if the element is not found after DOMContentLoaded. If all elements that we are trying to find are always there on page load, the mutation observer is never set up. Which is the case on Invidious.

This already happens in the current logic. It does an initial check before setting up listeners.

**Pull request merged**
